### ISSUE TITLE
luci-app-filebrowser启动后，进入界面 输入admin admin 但是提示“用户名或密码错误“ ！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [xiaozhuai/luci-app-filebrowser#2]
![image](https://user-images.githubusercontent.com/45259624/109674157-a570e800-7bb1-11eb-96e3-dc37dc032778.png)

**Comment by zhzh8015** [comment]
遇到同样的问题，希望能得到解决

**Comment by xiaozhuai** [comment]
@zxlhhyccc @zhzh8015 已修复

**Comment by zhzh8015** [comment]
> @zxlhhyccc @zhzh8015 已修复

感谢，已经成功登陆了！
